matrix:
  include:
    - language: node_js
      node_js:
          - "stable"
        script:
          - npm install
          - npm run build
          - npm run verify
          - npm run upload
      
    - language: csharp
      mono: none
      dotnet: 2.1.403
      script: 
        - dotnet run --project src\uploadimages\uploadimages.csproj
git:
   depth: 9999999  