matrix:
  include:
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - "node_modules"
      script: 
          - npm install
          - npm run build
          - npm run verify
          - npm run upload    

    - language: csharp
      mono: none
      dotnet: 2.1.403
      script:
        - dotnet run --project src\uploadimages\uploadimages.csproj
